monitor_addresses = [
    { name = "My Address", address = "0x461Fa03E15009DE866B0F6eC44E13e89B142CB61", alert_threshold = 3.0, symbol = "ETH", chain_id = 1 }
]

[exchange_difference]
[[exchange_difference.exchanges]]
name = "OKX"
url = "https://www.okx.com"
fee_rate = 0.07 # percent

[[exchange_difference.exchanges]]
name = "HashKey"
url = "https://api-pro.hashkey.com"
fee_rate = 0.0 # percent

[[exchange_difference.exchanges]]
name = "MEXC"
url = "https://api.mexc.com"
fee_rate = 0.0 # percent

[[exchange_difference.instruments]]
base_ccy = "USDC"
target_ccy = "ETH"

[[exchange_difference.instruments]]
base_ccy = "USDC"
target_ccy = "BTC"
